### ISSUE TITLE
Questions about the Code Replication

### ISSUE THREAD

**Issue by Liao-Jun** [saliteta/SA-GS-CODE#2]
I used the GauUsceneV2 dataset in the Mask Extraction step,  there are 33 images that cannot generate masks.The pictures are as follows.
DJI_20231218125804_0090_Zenmuse-L1-mission.JPG
DJI_20231218125141_0038_Zenmuse-L1-mission.JPG
DJI_20231218124856_0018_Zenmuse-L1-mission.JPG
DJI_20231218164839_0049_Zenmuse-L1-mission.JPG
DJI_20231218125815_0095_Zenmuse-L1-mission.JPG
DJI_20231217164423_0097_Zenmuse-L1-mission.JPG
DJI_20231218124831_0007_Zenmuse-L1-mission.JPG
DJI_20231218131349_0043_Zenmuse-L1-mission.JPG
DJI_20231218165248_0107_Zenmuse-L1-mission.JPG
DJI_20231218125807_0091_Zenmuse-L1-mission.JPG
DJI_20231218164834_0047_Zenmuse-L1-mission.JPG
DJI_20231218125810_0092_Zenmuse-L1-mission.JPG
DJI_20231218124922_0030_Zenmuse-L1-mission.JPG
DJI_20231218124919_0029_Zenmuse-L1-mission.JPG
DJI_20231218125147_0040_Zenmuse-L1-mission.JPG
DJI_20231218131404_0050_Zenmuse-L1-mission.JPG
DJI_20231218164846_0052_Zenmuse-L1-mission.JPG
DJI_20231218164843_0051_Zenmuse-L1-mission.JPG
DJI_20231218124909_0024_Zenmuse-L1-mission.JPG
DJI_20231218124914_0027_Zenmuse-L1-mission.JPG
DJI_20231218124828_0006_Zenmuse-L1-mission.JPG
DJI_20231218124910_0025_Zenmuse-L1-mission.JPG
DJI_20231218131339_0039_Zenmuse-L1-mission.JPG
DJI_20231218164525_0016_Zenmuse-L1-mission.JPG
DJI_20231218125813_0094_Zenmuse-L1-mission.JPG
DJI_20231218131027_0008_Zenmuse-L1-mission.JPG
DJI_20231218125149_0041_Zenmuse-L1-mission.JPG
DJI_20231218124836_0009_Zenmuse-L1-mission.JPG
DJI_20231218132046_0005_Zenmuse-L1-mission.JPG
DJI_20231218164841_0050_Zenmuse-L1-mission.JPG
DJI_20231218125811_0093_Zenmuse-L1-mission.JPG
DJI_20231218130141_0122_Zenmuse-L1-mission.JPG
DJI_20231218164832_0046_Zenmuse-L1-mission.JPG
Could you please tell me more details of the  Code Replication? Thanks

**Comment by saliteta** [comment]
If you mean that there is no mask for the ground, buildings, or vegetation in the above images, that is okay. Our algorithm does not guarantee that it will segment something from each image. What if there is no ground, vegetation, or building in a picture? Of course, there would be no mask there.

We have encountered this problem before, which is why we created a very robust training procedure. It will only constrain the points that have a mask. If there is no corresponding mask, the constraint is based only on the image.

**Comment by Liao-Jun** [comment]
thank you for your reply，I reproduced it again and found that in the third step, the following error occurred after 3900 iterations:
Training progress:  13%|█▎        | 3900/30000 [04:34<10:39, 40.79it/s, Loss=0.6774297]
Training progress:  13%|█▎        | 3900/30000 [04:34<10:39, 40.79it/s, Loss=nan]      
Training progress:  13%|█▎        | 3910/30000 [04:34<10:47, 40.31it/s, Loss=nan]
Training progress:  13%|█▎        | 3910/30000 [04:34<10:47, 40.31it/s, Loss=nan]
Training progress:  13%|█▎        | 3920/30000 [04:34<10:16, 42.31it/s, Loss=nan]shape loss out of bound [29/06 16:05:11]
Traceback (most recent call last):
  File "train.py", line 277, in <module>
    args.mask_path
  File "train.py", line 131, in training
    loss.backward()
  File "/home/ubuntu/anaconda3/envs/SA-GS/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/ubuntu/anaconda3/envs/SA-GS/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

For the 33 images that were not masked in the first step, I manually created masks with all values ​​of -1.

**Comment by saliteta** [comment]
Did you use multiple you to train one scene?

**Comment by saliteta** [comment]
I mean multiple GPUs to train one scene?

**Comment by Liao-Jun** [comment]
No, no, only one.

**Comment by Liao-Jun** [comment]
RTX4090

**Comment by saliteta** [comment]
Which scene? Did you try to run one scene for multiple times? Does it
always stop at iteration 3900?

As for my memory, I just encountered one time when I was using LFLS. A
simple retry will get you on ur way?

**Comment by saliteta** [comment]
If it does not work, please let me know. We will test and solve that
problem. One of my co worker is trying to reproduce the error.

**Comment by Liao-Jun** [comment]
Training progress:  10%|█         | 3090/30000 [04:23<13:37, 32.93it/s, Loss=0.5972668]
Training progress:  10%|█         | 3100/30000 [04:23<13:30, 33.17it/s, Loss=0.5972668]shape loss out of bound [29/06 16:46:07]
Traceback (most recent call last):
  File "train.py", line 277, in <module>
    args.mask_path
  File "train.py", line 131, in training
    loss.backward()
  File "/home/ubuntu/anaconda3/envs/SA-GS/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/ubuntu/anaconda3/envs/SA-GS/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: Function _RasterizeGaussiansBackward returned an invalid gradient at index 2 - got [0, 0, 3] but expected shape compatible with [0, 16, 3]
I re-executed and the first error occurred again.

**Comment by Liao-Jun** [comment]
The dataset is the lower campus in the GauUsceneV2 dataset

**Comment by Liao-Jun** [comment]
This error also occurred in the recurrence last week. At that time, I directly deleted the 33 pictures for the problem in the first step.

**Comment by Victor-Xiaoyu-Ye** [comment]
> thank you for your reply，I reproduced it again and found that in the third step, the following error occurred after 3900 iterations: Training progress: 13%|█▎ | 3900/30000 [04:34<10:39, 40.79it/s, Loss=0.6774297] Training progress: 13%|█▎ | 3900/30000 [04:34<10:39, 40.79it/s, Loss=nan] Training progress: 13%|█▎ | 3910/30000 [04:34<10:47, 40.31it/s, Loss=nan] Training progress: 13%|█▎ | 3910/30000 [04:34<10:47, 40.31it/s, Loss=nan] Training progress: 13%|█▎ | 3920/30000 [04:34<10:16, 42.31it/s, Loss=nan]shape loss out of bound [29/06 16:05:11] Traceback (most recent call last): File "train.py", line 277, in args.mask_path File "train.py", line 131, in training loss.backward() File "/home/ubuntu/anaconda3/envs/SA-GS/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs) File "/home/ubuntu/anaconda3/envs/SA-GS/lib/python3.7/site-packages/torch/autograd/**init**.py", line 175, in backward allow_unreachable=True, accumulate_grad=True) # Calls into the C++ engine to run the backward pass RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
> 
> For the 33 images that were not masked in the first step, I manually created masks with all values ​​of -1.

Hi! Thanks for following our work, we tested on a different conda environment, and got the same results.

However, with pytorch 2.3.0 with cuda 11.8, the train process is flawless. So we released our entire virtual environment and please try it out in the latest version of our code!

**Comment by Liao-Jun** [comment]
I am very sorry, but I still failed in the third step.
After about 700 iterations, the iteration speed suddenly became faster. I suspect that the number of Gaussians has decreased due to optimization.
Training progress:   2%|▏         | 660/30000 [02:53<2:14:20,  3.64it/s, Loss=0.8877702]
Training progress:   2%|▏         | 670/30000 [02:53<2:13:23,  3.66it/s, Loss=0.8877702]
Training progress:   2%|▏         | 670/30000 [02:54<2:13:23,  3.66it/s, Loss=0.9059126]
Training progress:   2%|▏         | 680/30000 [02:54<1:41:17,  4.82it/s, Loss=0.9059126]
Training progress:   2%|▏         | 680/30000 [02:54<1:41:17,  4.82it/s, Loss=0.9416119]
Training progress:   2%|▏         | 690/30000 [02:54<1:18:52,  6.19it/s, Loss=0.9416119]
Training progress:   2%|▏         | 690/30000 [02:55<1:18:52,  6.19it/s, Loss=0.9802656]
Training progress:   2%|▏         | 700/30000 [02:55<1:02:52,  7.77it/s, Loss=0.9802656]
Training progress:   2%|▏         | 700/30000 [02:55<1:02:52,  7.77it/s, Loss=0.8573489]
Training progress:   2%|▏         | 710/30000 [02:55<51:54,  9.40it/s, Loss=0.8573489]  
Training progress:   2%|▏         | 710/30000 [02:56<51:54,  9.40it/s, Loss=0.8005071]
Training progress:   2%|▏         | 720/30000 [02:56<43:59, 11.09it/s, Loss=0.8005071]
Training progress:   2%|▏         | 720/30000 [02:57<43:59, 11.09it/s, Loss=0.9172333]
Training progress:   2%|▏         | 730/30000 [02:57<38:09, 12.78it/s, Loss=0.9172333]

Then in subsequent iterations, loss finally becomes nan
Training progress:   4%|▍         | 1210/30000 [03:22<32:56, 14.57it/s, Loss=0.8081722]
Training progress:   4%|▍         | 1220/30000 [03:22<29:17, 16.38it/s, Loss=0.8081722]
Training progress:   4%|▍         | 1220/30000 [03:23<29:17, 16.38it/s, Loss=495.9788666]
Training progress:   4%|▍         | 1230/30000 [03:23<26:41, 17.96it/s, Loss=495.9788666]
Training progress:   4%|▍         | 1230/30000 [03:23<26:41, 17.96it/s, Loss=3.8462172]  
Training progress:   4%|▍         | 1240/30000 [03:23<24:56, 19.22it/s, Loss=3.8462172]
Training progress:   4%|▍         | 1240/30000 [03:24<24:56, 19.22it/s, Loss=786.4901990]
Training progress:   4%|▍         | 1250/30000 [03:24<28:44, 16.67it/s, Loss=786.4901990]
Training progress:   4%|▍         | 1250/30000 [03:24<28:44, 16.67it/s, Loss=nan]        
Training progress:   4%|▍         | 1260/30000 [03:24<26:21, 18.17it/s, Loss=nan]
Training progress:   4%|▍         | 1260/30000 [03:25<26:21, 18.17it/s, Loss=nan]

The dataset is Lower Campus in GauUscene.The results of the second step are as follows
ground,building,vegetation
0.15034890677971613,0.11066597605306414,0.1826652447237432

**Comment by saliteta** [comment]
Did you solve this problem. I cannot reproduce this error. Our clear stratgy should happen some where in 6000, 12000, 18000. 
As we shown here:
https://github.com/saliteta/SA-GS-CODE/blob/main/dynamic_training/train.py#L165

You might change a little bit about this line in your code, could you check it?

**Comment by Liao-Jun** [comment]
I'm really sorry, I changed two devices and used three different data sets, but the same result appeared. I didn't change any code, only the path-related commands.

**Comment by saliteta** [comment]
Thanks for following up, we did not encounter this problem in our environment. But regarding your question, it seems like the loss is unstable. 

We have encountered this problem several times in different repositories like LeGaussians and Some ancient NeRF methods. How about using this method:

https://github.com/buaavrcg/LEGaussians/issues/12

```
        total_loss = dataset.reconstruction_loss_weight * loss \
                    + dataset.semantic_loss_weight * semantic_loss \
                    + dataset.uncertainty_loss_weight * uncertainty_loss \
                    + dataset.xyzmlp_loss_weight * xyz_mlp_loss \
                    + dataset.smooth_loss_weight * smooth_loss
        
        total_loss.backward()
        
        torch.nn.utils.clip_grad_norm_(index_decoder.parameters(), max_norm=1)

        iter_end.record()
```

adding some clip_grad_norm to some of the parameters, it might solve the problem

**Comment by Liao-Jun** [comment]
Thank you very much for your positive response. I succeeded. I replaced the folder diff_gaussian_rasterization with the vanilla gaussian splatting, then added your changes and recompile it.There is no other change, I don't know why it works, it's magical.

**Comment by Richardder** [comment]
> Thank you very much for your positive response. I succeeded. I replaced the folder diff_gaussian_rasterization with the vanilla gaussian splatting, then added your changes and recompile it.There is no other change, I don't know why it works, it's magical.

Can you provide your solution? I came with the same problem. NaN occurs in Loss，and the rendered images are all dark.
